#!/usr/bin/env bash

if [ "${MODE}" = "DEV" ]; then
  esbuild \
  src/main.ts \
  --bundle \
  --platform=node \
  --target=es2020,node16 \
  --outfile=dist/bundle.js \
  --sourcemap=inline
else
  esbuild \
  src/main.ts \
  --bundle \
  --platform=node \
  --target=es2020,node16 \
  --outfile=dist/bundle.js \
  --minify
fi
