#!/usr/bin/env bash

tsc --outDir out/

if [ "${MODE}" = "DEV" ]; then
  esbuild \
  out/main.js \
  --bundle \
  --platform=node \
  --target=es2020,node16 \
  --outfile=dist/bundle.dev.js \
  --sourcemap=inline
else
  esbuild \
  out/main.js \
  --bundle \
  --platform=node \
  --target=es2020,node16 \
  --outfile=dist/bundle.js \
  --minify
fi

rm -rf out/
